const quotes = [
    {"text": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde"},
  {"text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill"},
  {"text": "Life is what happens when you're busy making other plans.", "author": "John Lennon"},
  {"text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt"},
  {"text": "You miss 100% of the shots you don't take.", "author": "Wayne Gretzky"},
  {"text": "Whether you think you can or you think you can't, you're right.", "author": "Henry Ford"},
  {"text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama"},
  {"text": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein"},
  {"text": "The best way to predict the future is to invent it.", "author": "Alan Kay"},
  {"text": "Dream big and dare to fail.", "author": "Norman Vaughan"},
  {"text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
  {"text": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson"},
  {"text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt"},
  {"text": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
  {"text": "Act as if what you do makes a difference. It does.", "author": "William James"},
  {"text": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman"},
  {"text": "Do not wait to strike till the iron is hot; but make it hot by striking.", "author": "William Butler Yeats"},
  {"text": "Everything you’ve ever wanted is on the other side of fear.", "author": "George Addair"},
  {"text": "The mind is everything. What you think you become.", "author": "Buddha"},
  {"text": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu"},
  {"text": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
  {"text": "Strive not to be a success, but rather to be of value.", "author": "Albert Einstein"},
  {"text": "Every moment is a fresh beginning.", "author": "T.S. Eliot"},
  {"text": "Turn your wounds into wisdom.", "author": "Oprah Winfrey"},
  {"text": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar"},
  {"text": "Believe in yourself and all that you are.", "author": "Christian D. Larson"},
  {"text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Unknown"},
  {"text": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson"},
  {"text": "Little by little, one travels far.", "author": "J.R.R. Tolkien"},
  {"text": "Keep going. Be all in.", "author": "Bryan Hutchinson"},
  {"text": "Opportunities don't happen. You create them.", "author": "Chris Grosser"},
  {"text": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill"},
  {"text": "Courage is resistance to fear, mastery of fear, not absence of fear.", "author": "Mark Twain"},
  {"text": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt"},
  {"text": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
  {"text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius"},
  {"text": "Dream big. Start small. Act now.", "author": "Robin Sharma"},
  {"text": "Everything has beauty, but not everyone sees it.", "author": "Confucius"},
  {"text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt"},
  {"text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis"},
  {"text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau"},
  {"text": "Do what you love, and you’ll never work a day in your life.", "author": "Confucius"},
  {"text": "Failure is the condiment that gives success its flavor.", "author": "Truman Capote"},
  {"text": "Happiness depends upon ourselves.", "author": "Aristotle"},
  {"text": "Don’t let yesterday take up too much of today.", "author": "Will Rogers"},
  {"text": "The best revenge is massive success.", "author": "Frank Sinatra"},
  {"text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis"},
  {"text": "I never dreamed about success. I worked for it.", "author": "Estee Lauder"},
  {"text": "The best time to plant a tree was 20 years ago. The second best time is now.", "author": "Chinese Proverb"},
  {"text": "Do not let what you cannot do interfere with what you can do.", "author": "John Wooden"},
  {"text": "Act as if what you do makes a difference. It does.", "author": "William James"},
  {"text": "Success is not in what you have, but who you are.", "author": "Bo Bennett"},
  {"text": "Your limitation—it’s only your imagination.", "author": "Unknown"},
  {"text": "Push yourself, because no one else is going to do it for you.", "author": "Unknown"},
  {"text": "Sometimes later becomes never. Do it now.", "author": "Unknown"},
  {"text": "Great things never come from comfort zones.", "author": "Unknown"},
  {"text": "Dream it. Wish it. Do it.", "author": "Unknown"},
  {"text": "Success doesn’t just find you. You have to go out and get it.", "author": "Unknown"},
  {"text": "Don’t stop when you’re tired. Stop when you’re done.", "author": "Marilyn Monroe"},
  {"text": "Wake up with determination. Go to bed with satisfaction.", "author": "Unknown"},
  {"text": "Do something today that your future self will thank you for.", "author": "Unknown"},
  {"text": "Little things make big days.", "author": "Unknown"},
  {"text": "It’s going to be hard, but hard does not mean impossible.", "author": "Unknown"},
  {"text": "Don’t wait for opportunity. Create it.", "author": "George Bernard Shaw"},
  {"text": "Sometimes you win, sometimes you learn.", "author": "John Maxwell"},
  {"text": "The harder the battle, the sweeter the victory.", "author": "Les Brown"},
  {"text": "Don’t limit your challenges. Challenge your limits.", "author": "Unknown"},
  {"text": "Do what is right, not what is easy nor what is popular.", "author": "Unknown"},
  {"text": "Success is the sum of small efforts repeated day in and day out.", "author": "Robert Collier"},
  {"text": "Great minds discuss ideas; average minds discuss events; small minds discuss people.", "author": "Eleanor Roosevelt"},
  {"text": "Turn your dreams into goals.", "author": "Unknown"},
  {"text": "Life is 10% what happens to us and 90% how we react to it.", "author": "Charles R. Swindoll"},
  {"text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
  {"text": "Don’t let the fear of losing be greater than the excitement of winning.", "author": "Robert Kiyosaki"},
  {"text": "The only person you should try to be better than is the person you were yesterday.", "author": "Unknown"},
  {"text": "Opportunities are usually disguised as hard work, so most people don’t recognize them.", "author": "Ann Landers"},
  {"text": "Don’t count the days, make the days count.", "author": "Muhammad Ali"},
  {"text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett"},
  {"text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt"},
  {"text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar"},
  {"text": "A year from now you may wish you had started today.", "author": "Karen Lamb"},
  {"text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt"},
  {"text": "Do what you can with all you have, wherever you are.", "author": "Theodore Roosevelt"},
  {"text": "Don’t wish it were easier. Wish you were better.", "author": "Jim Rohn"},
  {"text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs"},
  {"text": "Believe in your infinite potential. Your only limitations are those you set upon yourself.", "author": "Roy T. Bennett"},
  {"text": "Sometimes the smallest step in the right direction ends up being the biggest step of your life.", "author": "Naeem Callaway"},
  {"text": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi"},
  {"text": "Great things never come from comfort zones.", "author": "Unknown"},
  {"text": "Your limitation—it's only your imagination.", "author": "Unknown"},
  {"text": "Push yourself, because no one else is going to do it for you.", "author": "Unknown"},
  {"text": "Success is the sum of small efforts repeated day in and day out.", "author": "Robert Collier"},
  {"text": "Hustle in silence and let your success make the noise.", "author": "Frank Ocean"},
  {"text": "Do not wait to strike till the iron is hot; but make it hot by striking.", "author": "William Butler Yeats"},
  {"text": "A goal is a dream with a deadline.", "author": "Napoleon Hill"},
  {"text": "Motivation is what gets you started. Habit is what keeps you going.", "author": "Jim Rohn"},
  {"text": "It always seems impossible until it's done.", "author": "Nelson Mandela"},
  {"text": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt"},
  {"text": "Perceive that which cannot be seen with the eye.", "author": "Miyamoto Musashi"},
  {"text": "In battle, if you make your opponent flinch, you have already won.", "author": "Sun Tzu"},
  {"text": "Opportunities multiply as they are seized.", "author": "Sun Tzu"},
  {"text": "Do not fear death, but rather the unlived life.", "author": "Miyamoto Musashi"},
  {"text": "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", "author": "Sun Tzu"},
  {"text": "Perfection is attained not when there is nothing more to add, but when there is nothing more to take away.", "author": "Miyamoto Musashi"},
  {"text": "He who is prudent and lies in wait for an enemy who is not, will be victorious.", "author": "Sun Tzu"},
  {"text": "Appear at points which the enemy must hasten to defend; march swiftly to places where you are not expected.", "author": "Sun Tzu"},
  {"text": "The ultimate aim of martial arts is not having to use them.", "author": "Miyamoto Musashi"},
  {"text": "If you know the enemy and know yourself, you need not fear the result of a hundred battles.", "author": "Sun Tzu"},
  {"text": "When you surround an army, leave an outlet free. Do not press a desperate foe too hard.", "author": "Sun Tzu"},
  {"text": "The wise warrior avoids the battle.", "author": "Miyamoto Musashi"},
  {"text": "Opportunities are seized by those who are ready, not by those who wait.", "author": "Napoleon Bonaparte"},
  {"text": "A leader is a dealer in hope.", "author": "Napoleon Bonaparte"},
  {"text": "In war, the moral is to the physical as three is to one.", "author": "Napoleon Bonaparte"},
  {"text": "Do not fight a battle if you don’t gain anything by winning.", "author": "Sun Tzu"},
  {"text": "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.", "author": "Sun Tzu"},
  {"text": "The greatest victory is that which requires no battle.", "author": "Sun Tzu"},
  {"text": "He who wishes to be obeyed must know how to command.", "author": "Napoleon Bonaparte"},
  {"text": "Polish your sword and sharpen your mind.", "author": "Miyamoto Musashi"}
];
export default quotes;